- name: copy logstach config file
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: restart logstash service
  systemd:
    name: logstash
    state: restart
    enabled: yes