---

- name: checking roles
  hosts: all
  become: true

  tasks:
    - name: install the httpd
      tags:
        - httpd
      roles:
        - httpd

    - name: copy the file
      tags:
        - copy
      roles: 
        Copy 