- name: roboshop project setup - frontend
  hosts: KARTHEEK
  tags:
   - frontend
  become: yes
  roles:
   - frontend
- name: roboshop project setup - mongodb
  hosts: MONGODB
  tags:
   - mongodb
  become: yes
  roles:
    - mongodb
- name: roboshop project setup - catalogue
  hosts: CATALOGUE
  tags:
   - catalogue
  become: yes
  roles:
    - catalogue
- name: roboshop project setup - redis
  hosts: REDIS
  tags:
   - redis
  become: yes
  roles:
    - redis
- name: roboshop project setup - user
  hosts: USER
  tags:
   - user
  become: yes
  roles:
    - user
- name: roboshop project setup - cart
  hosts: CART
  tags:
   - cart
  become: yes
  roles:
    - cart
- name: roboshop project setup - mysql
  hosts: MYSQL
  tags:
   - mysql
  roles:
    - mysql
- name: roboshop project setup - shipping
  hosts: SHIPPING
  tags:
   - shipping
  become: yes
  roles:
    - shipping
- name: roboshop project setup - rabbitmq
  hosts: RABBITMQ
  roles:
    - rabbitmq
  tags:
   - rabbitmq
  become: yes
- name: roboshop project setup - payment
  hosts: PAYMENT
  tags:
   - payment
  become: yes
  roles:
    - payment