- name: demo on variable using ansible
  hosts: all
  vars:
   URL1: play.google.come
   
   task:
    - name: print varible from play
      debug:
        msg: URL = {{URL1}}
    - name: print variable form file
      debug:
        msg: URL = {{URL2}}