- name: demo on variable using ansible
  hosts: all
  vars:
    URL1: play.google.come
    URL: play.google.com
  vars_files:
    - vars-1.yml
  tasks:
  - name: print varible from play
    debug:
      msg: URL = {{URL1}}
  - name: print variable form file
    debug:
      msg: URL = {{URL2}}
  - name: task level variable
    vars:
      URL3: task.google.come
      URL: task.google.com
    debug:
      msg: URL = {{URL3}}
  - name: host level variables
    debug:
      msg: URL = {{URL4}}
  - name: commanline level variables
    debug:
      msg: URL = {{URL5}}
  - name: procedence check in variables
    debug:
      msg: URL = {{URL}}
    
    
  roles:
   - sample
      
      