
# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: log
  enabled: true
  json.keys_under_root: true
  paths:
    - /var/log/{{component}}.log
    
  setup.template.name: "{{component"
  setup.template.pattern: "{{component}}-*"
  setup.ilm.enabled: false


# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["elasticsearch.roboshop.internal:9200"]
  index: "{{component}}-%{+yyyy.MM.dd}"

  
# ------------------------------ Logstash Output -------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

