- name: Copy MySQL Repo
  copy:
   src: mysql.repo
   dest: /etc/yum.repos.d/mysql.repo
    
#- name: Remove mariadb-libs Package
  yum:
    name: mariadb-libs
    state: absent
    
- name: Installing mysql community
  yum: 
   name: mysql-community-server
   state: present
   
- name: starting mysql services
  systemd:
    name: mysqld
    state: present
    enabled: yes
    
- name: Grab default password
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: default_pass
   
- name: reset SQL files
  copy:
   src: reset.sql
   dest: /tmp/reset.sql
   
- name: Reset Mysql password
  shell: --connect-expired-password -u root -p"${DEFAULT_PASSWORD}" </tmp/reset.sql