- name: update prometheus config
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml/
    become: true
    
- name: restart prometheus server
  systemd:
    state: restarted
    enabled: yes