- name: update prometheus config
  file:
    name: template
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    remote_src: yes
    
- name: restart prometheus server
  systemd:
    state: restarted
    enabled: yes