- name: update prometheus config
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    become: true
    
- name: restart prometheus server
  systemd:
    state: restarted
    enabled: yes