- name: Import filebeat RPM key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    
- name: copy from repo filebeat
  copy:
   src: es.repo
   dest: /etc/yum.repos.d/es.repo
   
- name: Install filebeat
  yum:
    name: filebeat
    state: installed
    update_cache: yes
   
- name: starting filebeat service
  systemd:
    name: filebeat
    state: restarted
    enabled: yes